name_or_path: /root/models/mistralai/Mistral-7B-Instruct-v0.1
tokenizer_name_or_path: null
archive: null
block_name: MistralDecoderLayer

policy_dtype: float32
fsdp_policy_mp: null
reference_dtype: float16