name_or_path: /workspace/panleyi/models/Qwen/Qwen2.5-3B-sft
tokenizer_name_or_path: null
archive: null
block_name: Qwen2DecoderLayer

policy_dtype: float32
fsdp_policy_mp: null
reference_dtype: float16