name: WSPIN
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
dependencies:
  - python=3.9
  - pip=23.0
  - cudatoolkit=11.8
  - pytorch>=2.1.0 
  - numpy
  - pip:
    - -i https://pypi.tuna.tsinghua.edu.cn/simple
    - transformers>=4.31.0
    - datasets>=2.12.0
    - hydra-core>=1.3.2
    - omegaconf>=2.3.0
    - wandb>=0.15.4
    - tqdm>=4.65.0
    - accelerate>=0.20.3
    - bs4>=0.0.1
    - beautifulsoup4>=4.12.2
    - tensor-parallel>=1.3.0
    - sentencepiece>=0.1.99
    - protobuf>=4.23.3
    - fschat[model_worker,webui]
    - vllm
    - torchaudio
    - torchvision
